### ISSUE TITLE
numpy 2.4.0 fails on deprecated np.trapz

### ISSUE THREAD

**Issue by SharonkBrain** [neuropsychology/NeuroKit#1155]
Describe the bug

NeuroKit raises an AttributeError when running functions that rely on np.trapz with NumPy ≥ 2.4.0. Starting from NumPy 2.4.0, numpy.trapz is no longer available, which causes NeuroKit to crash at runtime instead of performing numerical integration.

Error message:
AttributeError: module 'numpy' has no attribute 'trapz'

To Reproduce

Minimal reproducible example:

import neurokit2 as nk
import numpy as np

signal = np.sin(np.linspace(0, 10, 1000))

Any NeuroKit function that internally uses np.trapz
nk.signal_power(signal)

Environment:
NumPy 2.4.0+
NeuroKit2 (latest pip version at time of writing)

Running this code raises the error shown above.

Expected behaviour

NeuroKit should work correctly with NumPy ≥ 2.4.0 and perform trapezoidal integration without raising an exception.

Suggested fixes include replacing np.trapz with scipy.integrate.trapezoid, providing an internal fallback implementation if SciPy is not available, or explicitly restricting NumPy to <2.4.0 with a clear error message.

Screenshots

Not applicable (Python exception only).

System Specifications

Run:

import neurokit2 as nk
nk.version()

Paste the output here.

Also run:

import numpy as np
np.__version__

Output:
2.4.0

**Comment by SharonkBrain** [comment]
Thanks, @DerAndereJohannes — this is exactly what I was looking for. Appreciate the quick help!

**Comment by DerAndereJohannes** [comment]
Thank you again for the report. The newest version of NeuroKit2 (0.2.13) fixes the trapz issue. Please update to the latest version!

**Comment by SharonkBrain** [comment]
Many thanks!
