### ISSUE TITLE
NeuroKit not working with Pandas 3

### ISSUE THREAD

**Issue by tkerwin** [neuropsychology/NeuroKit#1162]
I haven't made a comprehensive test of the full suite, but the EDA processing portion is not working with Pandas 3.0 which was released last month. It uses the `DataFrame.pad` function that has been depreciated since Pandas 2.0 and has finally been removed:

```
File "C:\work\git\DADS-analysis\.venv\Lib\site-packages\neurokit2\eda\eda_process.py", line 86, in eda_process
    eda_cleaned = eda_clean(
        eda_signal,
    ...<2 lines>...
        **methods["kwargs_cleaning"],
    )
  File "C:\work\git\DADS-analysis\.venv\Lib\site-packages\neurokit2\eda\eda_clean.py", line 74, in eda_clean
    eda_signal = _eda_clean_missing(eda_signal)
  File "C:\work\git\DADS-analysis\.venv\Lib\site-packages\neurokit2\eda\eda_clean.py", line 94, in _eda_clean_missing
    eda_signal = pd.DataFrame.pad(pd.Series(eda_signal))
                 ^^^^^^^^^^^^^^^^
AttributeError: type object 'DataFrame' has no attribute 'pad'
```

I realize that getting everything working for Pandas 3 may take some time, but in the meantime it would be nice for your users to put out a wheel that enforces a requirement of Pandas version less than 3.

**Comment by DerAndereJohannes** [comment]
Thank you again for the report. The newest version of NeuroKit2 (0.2.13) uses a valid pandas version (< 3.0). Please update to the latest version!
